apiVersion: v1
kind: Secret
metadata:
  name: example-mongo-instance2-credentials
  namespace: default
type: Opaque
data:
  username: c3VwZXJhZG1pbg==
  password: c3VwZXJwYXNz
---
apiVersion: mongo.miguelgarcia.dev/v1
kind: MongoInstance
metadata:
  name: example-mongo-instance2
  namespace: default
spec:
  version: "8.0.6"
  storageSize: "10Gi"
  credentialsSecret: example-mongo-instance2-credentials
