apiVersion: v1
kind: Secret
metadata:
  name: example-mongo-instance2-credentials
  namespace: default
type: Opaque
data:
  username: c3VwZXJhZG1pbg==    # base64 for "superadmin"
  password: c3VwZXJwYXNz    # base64 for "superpass"
---
apiVersion: mongo.miguelgarcia.dev/v1
kind: MongoInstance
metadata:
  name: example-mongo-instance2
  namespace: default
spec:
  version: "8.0"
  storageSize: "10Gi"
  credentialsSecret: example-mongo-instance2-credentials
