apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mongoinstances.mongo.miguelgarcia.dev
spec:
  group: mongo.miguelgarcia.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - version
                - storageSize
                - credentialsSecret
              properties:
                version:
                  type: string
                storageSize:
                  type: string
                credentialsSecret:
                  type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: mongoinstances
    singular: mongoinstance
    kind: MongoInstance
    shortNames:
    - mongoinstance