---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "mongoinstance-operator"
  name: mongoinstance-operator-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongo-operator-cluster-role
rules:
  - apiGroups: ["mongo.miguelgarcia.dev"]
    resources: ["mongoinstances"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mongoinstance-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mongo-operator-cluster-role
subjects:
  - kind: ServiceAccount
    name: mongoinstance-operator-account
    namespace: "mongoinstance-operator"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoinstance-operator
  namespace: "mongoinstance-operator"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: mongoinstance-operator
  template:
    metadata:
      labels:
        application: mongoinstance-operator
    spec:
      serviceAccountName: mongoinstance-operator-account
      containers:
      - name: controller
        image: my-mongo-operator:local
        imagePullPolicy: Never # enable this line if you are using local image, like in microk8s